# Generated by Django 6.0.5 on 2026-06-02 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('agent_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('OPTIMIZING', 'Optimizing'), ('MONITORING', 'Monitoring'), ('INACTIVE', 'Inactive')], default='MONITORING', max_length=16)),
                ('est_savings', models.CharField(blank=True, default='', max_length=16)),
                ('active_rules', models.IntegerField(default=0)),
                ('failure_risk', models.IntegerField(default=0)),
                ('failure_risk_label', models.CharField(blank=True, default='', max_length=32)),
                ('backup_status', models.CharField(blank=True, default='', max_length=16)),
                ('network_stability', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'api_agent',
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('alert_type', models.CharField(choices=[('error', 'Error'), ('warn', 'Warning'), ('info', 'Info')], default='info', max_length=8)),
                ('timestamp_label', models.CharField(default='Just now', max_length=64)),
                ('is_simulated', models.BooleanField(default=False)),
                ('ai_diagnostic', models.TextField(blank=True, default='')),
                ('ai_resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('report_type', models.CharField(max_length=128)),
                ('date_generated', models.CharField(max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('occupancy_label', models.CharField(default='Low (0%)', max_length=32)),
                ('occupancy_value', models.IntegerField(default=0)),
                ('temp', models.FloatField(default=22.0)),
                ('temp_set', models.FloatField(default=22.0)),
                ('humidity', models.FloatField(default=50.0)),
                ('consumption_label', models.CharField(default='Expected (0kW)', max_length=32)),
                ('consumption_value', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPTIMAL', 'Optimal'), ('INEFFICIENT', 'Inefficient Use'), ('CRITICAL', 'Critical Error')], default='OPTIMAL', max_length=16)),
                ('status_label', models.CharField(default='Optimal', max_length=32)),
                ('ai_recommendation', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_zone',
                'ordering': ['zone_id'],
            },
        ),
        migrations.CreateModel(
            name='AgentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('enabled', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='api.agent')),
            ],
            options={
                'db_table': 'api_agent_control',
                'ordering': ['control_id'],
                'unique_together': {('agent', 'control_id')},
            },
        ),
    ]
