# Generated by Django 6.0.5 on 2026-06-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_id', models.CharField(max_length=64, unique=True)),
                ('anomaly_type', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='high', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('resolved', 'Resolvida'), ('dismissed', 'Descartada')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('diagnostic', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('savings_impact', models.TextField(blank=True, default='')),
                ('zone_snapshot_before', models.JSONField(blank=True, default=dict)),
                ('zone_snapshot_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_records', to='api.alert')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='api.zone')),
            ],
            options={
                'verbose_name_plural': 'anomalies',
                'db_table': 'api_anomaly',
                'ordering': ['-created_at'],
            },
        ),
    ]
